name: CI/CD Pipeline with CodeDeploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::249415164040:role/github-pipeline
          aws-region: us-east-1

      - name: Create deployment package
        run: zip -r deployment.zip . -x "*.git*" "node_modules/*"

      - name: Upload to S3
        run: aws s3 cp deployment.zip s3://johanna1983/deployment.zip

      - name: Trigger CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name galaxy-deployment \
            --deployment-group-name galaxy-deployment-goup \
            --s3-location bucket=johanna1983,key=deployment.zip,bundleType=zip \
            --region us-east-1
            # fin
